# Site settings
title: BY Blog
SEOTitle: 孤茕的博客 | BY Blog
header-img: img/post-bg-desk.jpg
email: lonelyxiya@qq.com
description: "Every failure is leading towards success."
keyword: "BY, BY Blog, 孤茕的博客, qiubaiying, 邱柏荧, iOS, Apple, iPhone"
url: "https://lonelyxiya.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/lonelyxiya/lonelyxiya.github.io.git" # you code repository


theme: jekyll-theme-cayman